Created ProtoInput
dgunther2001/Software_Engineering_2024 pull request #18
Opened 2024-09-14 23:24 UTC by Nikolas023

I created ProtoInput and added javadoc comments to it. This will get the user input. In ProtoUser, a compute request will be sent to the compute engine, which will determine if the input is valid or not using the AckToken.

2024-09-14 23:32 UTC, dgunther2001 requested changes
This looks good, but please add apis in the compute initializer to receive user requests and also send a result back to the user. Please add config files into the gitignore as this will affect nico and I's eclipse config and potentially break it. Also, please check the actions logs for where javadoc comments are missing. The logic here is great, just a few things to check on and add.

2024-09-14 23:32 UTC, dgunther2001 commented on .classpath
Add to gitignore

2024-09-14 23:32 UTC, dgunther2001 commented on .project
Add to gitignore

2024-09-14 23:32 UTC, dgunther2001 commented on .settings/org.eclipse.buildship.core.prefs
Add to gitignore

2024-09-14 23:32 UTC, dgunther2001 commented on src/Engine/AckToken.java
Looks great!

2024-09-14 23:32 UTC, dgunther2001 commented on src/Engine/ProtoUser.java
Checkstyle fails because it wants comment above the function

2024-09-14 23:32 UTC, dgunther2001 commented on src/engine/ProtoInput.java
Function needs javadoc to pass checkstyle

2024-09-14 23:32 UTC, dgunther2001 commented on src/Engine/AckToken.java
Missing javadoc comments though (check checkstyle failure log for exact locations)

2024-09-15 02:55 UTC, Nikolas023 commented
> This looks good, but please add apis in the compute initializer to receive user requests and also send a result back to the user. Please add config files into the gitignore as this will affect nico and I's eclipse config and potentially break it. Also, please check the actions logs for where javadoc comments are missing. The logic here is great, just a few things to check on and add.

Just updated everything!

2024-09-15 12:42 UTC, dgunther2001 approved these changes
LGTM. Consider adding a req and res function to the compute initializer as the api needs to work on both ends, not just in the user end.

2024-09-15 12:42 UTC, merged