layout dataStore api implementation logic
dgunther2001/Software_Engineering_2024 pull request #34
Opened 2024-09-27 02:08 UTC by NicoPotamus

Can you just verify that my logic is coherent. If so I'll implement what I can in the class and controller.

2024-09-27 18:01 UTC, dgunther2001 requested changes
The data processing needs to actually occur. The data storage request is returning null. In addition, this needs to be connected to the controller. If you make the adjusted changes, I can connect it to the controller over the weekend.

2024-09-27 18:01 UTC, dgunther2001 commented on src/engine/dataapi/DataStore.java
> +    public DataStream receiveDataRequest(DataStream newData, String id) {
This needs to do its job and actually store the value

2024-09-27 18:01 UTC, dgunther2001 commented on src/engine/dataapi/DataStream.java
> +    private List<String> data = new ArrayList<>();
Data stream should be an individual value, not an away. We should wrap the final request back to the controller after all data has been processed into a completely separate interface

2024-09-27 18:01 UTC, dgunther2001 commented on src/engine/dataapi/DataStream.java
> +    private List<String> data = new ArrayList<>();
Actually nvm, we discussed this and decided on single element lists

2024-09-27 18:01 UTC, dgunther2001 commented on src/engine/dataapi/DataStream.java
> +    public List<String> getData() {
Not: add javadoc

2024-09-27 18:01 UTC, dgunther2001 commented on src/engine/dataapi/DataStream.java
> +    public void setData(List<String> data) {
Nit: add javadoc

2024-09-27 18:01 UTC, dgunther2001 commented on src/engine/dataapi/DataStore.java
> +	List<Integer> data;
Nit: add javadoc

2024-09-27 18:01 UTC, dgunther2001 commented on src/engine/dataapi/ProtoDataStream.java
> +
Nit: add javadoc

2024-09-28 18:26 UTC, Nikolas023 commented on src/engine/dataapi/DataStore.java
> +    public DataStream receiveDataRequest(DataStream newData, String id) {
I agree!

2024-09-29 13:31 UTC, dgunther2001 approved these changes
This needs to be connected to the controller, and tests need to be reenabled, but I will do that today and make a pr. They are all quick fixes. The data store method also needs an overloaded version that deals with the simple string representation because right now the file objects break the system. Nonetheless, it doesn't introduce any breaking changes, so I'm gonna pull it in and make a few changes in a new branch.

2024-09-29 13:31 UTC, dgunther2001 commented on src/engine/dataapi/DataStore.java
> +    	}
Bring catch up next to '}'

2024-09-29 13:31 UTC, dgunther2001 commented on src/engine/dataapi/DataStore.java
> +    		 if(fileObject == null) {//if list wasn't started make a new one
Bring if up to '}'

2024-09-29 13:31 UTC, dgunther2001 commented on src/engine/dataapi/DataStore.java
> +    			 catch (IOException | ClassNotFoundException e) {
Bring catch up to '}'

2024-09-29 13:31 UTC, dgunther2001 commented on src/engine/dataapi/DataStore.java
> +        // search db or file for id
We're not rrying serialize things yet, and this adds some over complication as we're not using a raw string anymore which kind of breaks the system.

2024-09-29 13:31 UTC, merged